export const ENV_KEYS = {
  DATABASE_URL: 'DATABASE_URL',
  NODE_ENV: 'NODE_ENV',
  PORT: 'PORT',
  PARTNER_URL: 'PARTNER_URL',
  CLIENT_URL: 'CLIENT_URL',
  ADMIN_URL: 'ADMIN_URL',
  JWT_SECRET: 'JWT_SECRET',
  JWT_EXPIRES_IN: 'JWT_EXPIRES_IN',
  JWT_REFRESH_SECRET: 'JWT_REFRESH_SECRET',
  JWT_REFRESH_EXPIRES_IN: 'JWT_REFRESH_EXPIRES_IN',
} as const;
